-- MySQL Script generated by MySQL Workbench
-- Tue Oct 10 22:09:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
create database soccer;
use soccer;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`presidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`presidente` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Equipo` VARCHAR(45) NULL,
  `Fecha_nacimiento` DATETIME NULL,
  `Fecha_ingreso` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `equipo_local` VARCHAR(45) NOT NULL,
  `equipo_visitante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipo` (
  `equipo_id` INT NOT NULL AUTO_INCREMENT,
  `estadio` VARCHAR(45) NULL,
  `aforo` INT NOT NULL,
  `fecha fundacion` DATETIME NULL,
  `ciudad` VARCHAR(45) NULL,
  `presidente_DNI1` INT NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`equipo_id`),
  INDEX `fk_equipo_presidente1_idx` (`presidente_DNI1` ASC) VISIBLE,
  INDEX `fk_equipo_partido1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_presidente1`
    FOREIGN KEY (`presidente_DNI1`)
    REFERENCES `mydb`.`presidente` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipo_partido1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `mydb`.`partido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jugador` (
  `jugador_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `equipo` VARCHAR(45) NULL,
  `posicion` VARCHAR(45) NULL,
  `gol_id` VARCHAR(45) NULL,
  `equipo_equipo_id` INT NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`jugador_id`),
  INDEX `fk_jugador_equipo1_idx` (`equipo_equipo_id` ASC) VISIBLE,
  INDEX `fk_jugador_partido1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_jugador_equipo1`
    FOREIGN KEY (`equipo_equipo_id`)
    REFERENCES `mydb`.`equipo` (`equipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jugador_partido1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `mydb`.`partido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gol` (
  `IdGol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `minuto` VARCHAR(45) NULL,
  `jugador_jugador_id` INT NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`IdGol`),
  INDEX `fk_gol_jugador1_idx` (`jugador_jugador_id` ASC) VISIBLE,
  INDEX `fk_gol_partido1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_gol_jugador1`
    FOREIGN KEY (`jugador_jugador_id`)
    REFERENCES `mydb`.`jugador` (`jugador_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gol_partido1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `mydb`.`partido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
gol