/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.soccergui;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.views.*;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author torre
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        initStyles();
        initContent();
    }
    private void initStyles() {
              
       mensaje.putClientProperty("FlatLaf.style", "font: 16 $light.font");
       mensaje.setForeground(Color.black);
   
    }
    private void initContent() {
        showJPanel(new mainPage());
        textHeader.setText("Home page");
    }
    public static void showJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        button_teams = new javax.swing.JButton();
        button_players = new javax.swing.JButton();
        button_teamMatch = new javax.swing.JButton();
        button_presidents = new javax.swing.JButton();
        button_goals = new javax.swing.JButton();
        button_top3 = new javax.swing.JButton();
        button_mainPage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        textHeader = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 800));
        setPreferredSize(new java.awt.Dimension(1020, 500));

        JPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(230, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(2.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 600));

        button_teams.setBackground(new java.awt.Color(255, 0, 0));
        button_teams.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_teams.setForeground(new java.awt.Color(255, 255, 255));
        button_teams.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equipo.png"))); // NOI18N
        button_teams.setText("Equipos");
        button_teams.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_teams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_teams.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_teams.setIconTextGap(10);
        button_teams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_teamsActionPerformed(evt);
            }
        });

        button_players.setBackground(new java.awt.Color(255, 0, 0));
        button_players.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_players.setForeground(new java.awt.Color(255, 255, 255));
        button_players.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador-de-futbol.png"))); // NOI18N
        button_players.setText("Jugadores");
        button_players.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_players.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_players.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_players.setIconTextGap(10);
        button_players.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_playersActionPerformed(evt);
            }
        });

        button_teamMatch.setBackground(new java.awt.Color(255, 0, 0));
        button_teamMatch.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_teamMatch.setForeground(new java.awt.Color(255, 255, 255));
        button_teamMatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/juego.png"))); // NOI18N
        button_teamMatch.setText("Partidos");
        button_teamMatch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_teamMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_teamMatch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_teamMatch.setIconTextGap(10);
        button_teamMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_teamMatchActionPerformed(evt);
            }
        });

        button_presidents.setBackground(new java.awt.Color(255, 0, 0));
        button_presidents.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_presidents.setForeground(new java.awt.Color(255, 255, 255));
        button_presidents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidente.png"))); // NOI18N
        button_presidents.setText("Presidentes");
        button_presidents.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_presidents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_presidents.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_presidents.setIconTextGap(10);
        button_presidents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_presidentsActionPerformed(evt);
            }
        });

        button_goals.setBackground(new java.awt.Color(255, 0, 0));
        button_goals.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_goals.setForeground(new java.awt.Color(255, 255, 255));
        button_goals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poste-de-la-meta.png"))); // NOI18N
        button_goals.setText("Goles");
        button_goals.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_goals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_goals.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_goals.setIconTextGap(10);
        button_goals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_goalsActionPerformed(evt);
            }
        });

        button_top3.setBackground(new java.awt.Color(255, 0, 0));
        button_top3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_top3.setForeground(new java.awt.Color(255, 255, 255));
        button_top3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trofeo.png"))); // NOI18N
        button_top3.setText("Top 3");
        button_top3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_top3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_top3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_top3.setIconTextGap(10);
        button_top3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_top3ActionPerformed(evt);
            }
        });

        button_mainPage.setBackground(new java.awt.Color(255, 0, 0));
        button_mainPage.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        button_mainPage.setForeground(new java.awt.Color(255, 255, 255));
        button_mainPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/estadio.png"))); // NOI18N
        button_mainPage.setText("Principal");
        button_mainPage.setToolTipText("Hola, esta es la pagina principal.");
        button_mainPage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(255, 0, 0)));
        button_mainPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_mainPage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_mainPage.setIconTextGap(10);
        button_mainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mainPageActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SoccerGUI");

        jSeparator1.setAlignmentX(2.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_players, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_teams, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_teamMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_presidents, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_top3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(button_mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_players, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_teams, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_teamMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_presidents, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_goals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(button_top3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        textHeader.setBackground(new java.awt.Color(255, 255, 255));
        textHeader.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        textHeader.setForeground(new java.awt.Color(255, 255, 255));
        textHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addContainerGap())
        );

        mensaje.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        mensaje.setForeground(new java.awt.Color(0, 0, 0));
        mensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botas-de-futbol.png"))); // NOI18N
        mensaje.setText("FUTBOL PROFESIONAL COLOMBIANO-FPC");

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mensaje))
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(mensaje)
                .addGap(6, 6, 6)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_teamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_teamsActionPerformed
        // TODO add your handling code here:
        showJPanel(new teamsTable());
        textHeader.setText("Equipos");
        
    }//GEN-LAST:event_button_teamsActionPerformed

    private void button_presidentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_presidentsActionPerformed
        // TODO add your handling code here:
        showJPanel(new presidentTable());
         textHeader.setText("Presidentes");
        
    }//GEN-LAST:event_button_presidentsActionPerformed

    private void button_top3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_top3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_top3ActionPerformed

    private void button_mainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mainPageActionPerformed
        // TODO add your handling code here:
         showJPanel(new mainPage());
         textHeader.setText("Home page");
         
    }//GEN-LAST:event_button_mainPageActionPerformed

    private void button_playersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_playersActionPerformed
        // TODO add your handling code here:
        showJPanel(new playersTable());
        textHeader.setText("Jugadores");
    }//GEN-LAST:event_button_playersActionPerformed

    private void button_teamMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_teamMatchActionPerformed
        // TODO add your handling code here:
        showJPanel(new matchesTable());
        textHeader.setText("Partidos");
    }//GEN-LAST:event_button_teamMatchActionPerformed

    private void button_goalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_goalsActionPerformed
        // TODO add your handling code here:
        showJPanel(new goalTable());
        textHeader.setText("Partidos");
    }//GEN-LAST:event_button_goalsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton button_goals;
    private javax.swing.JButton button_mainPage;
    private javax.swing.JButton button_players;
    private javax.swing.JButton button_presidents;
    private javax.swing.JButton button_teamMatch;
    private javax.swing.JButton button_teams;
    private javax.swing.JButton button_top3;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel textHeader;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel( new FlatMaterialLighterIJTheme() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            new dashboard().setVisible(true);
        });
    }
    // Variables declaration - do not modify
   
    // End of variables declaration

    
}
