/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import static com.mycompany.soccergui.dashboard.showJPanel;

/**
 *
 * @author torre
 */
public class goalTable extends javax.swing.JPanel {

    /**
     * Creates new form playersForm
     */
    public goalTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        saearchFieldGoal = new javax.swing.JTextField();
        searchGoal = new javax.swing.JButton();
        tableGoal = new javax.swing.JScrollPane();
        tablePlayers = new javax.swing.JTable();
        createGoal = new javax.swing.JButton();
        updateGoal = new javax.swing.JButton();
        deleteGoal = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(255, 255, 255));

        saearchFieldGoal.setBackground(new java.awt.Color(255, 255, 255));
        saearchFieldGoal.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        saearchFieldGoal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saearchFieldGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        searchGoal.setBackground(new java.awt.Color(255, 0, 0));
        searchGoal.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        searchGoal.setForeground(new java.awt.Color(255, 255, 255));
        searchGoal.setText("Buscar");
        searchGoal.setBorder(new javax.swing.border.MatteBorder(null));
        searchGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGoalActionPerformed(evt);
            }
        });

        tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Gol ID", "Jugador", "Minuto", "Partido"
            }
        ));
        tableGoal.setViewportView(tablePlayers);

        createGoal.setBackground(new java.awt.Color(255, 0, 0));
        createGoal.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        createGoal.setForeground(new java.awt.Color(255, 255, 255));
        createGoal.setText("Crear");
        createGoal.setBorder(new javax.swing.border.MatteBorder(null));
        createGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGoalActionPerformed(evt);
            }
        });

        updateGoal.setBackground(new java.awt.Color(255, 0, 0));
        updateGoal.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        updateGoal.setForeground(new java.awt.Color(255, 255, 255));
        updateGoal.setText("Actualizar");
        updateGoal.setBorder(new javax.swing.border.MatteBorder(null));
        updateGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGoalActionPerformed(evt);
            }
        });

        deleteGoal.setBackground(new java.awt.Color(255, 0, 0));
        deleteGoal.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        deleteGoal.setForeground(new java.awt.Color(255, 255, 255));
        deleteGoal.setText("Borrar");
        deleteGoal.setBorder(new javax.swing.border.MatteBorder(null));
        deleteGoal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGoalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(saearchFieldGoal)
                        .addGap(18, 18, 18)
                        .addComponent(searchGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addComponent(tableGoal, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saearchFieldGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(tableGoal, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchGoalActionPerformed

    private void createGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGoalActionPerformed
        // TODO add your handling code here:
        showJPanel(new goalForm());
    }//GEN-LAST:event_createGoalActionPerformed

    private void updateGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateGoalActionPerformed

    private void deleteGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteGoalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton createGoal;
    private javax.swing.JButton deleteGoal;
    private javax.swing.JTextField saearchFieldGoal;
    private javax.swing.JButton searchGoal;
    private javax.swing.JScrollPane tableGoal;
    private javax.swing.JTable tablePlayers;
    private javax.swing.JButton updateGoal;
    // End of variables declaration//GEN-END:variables
}
