/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import static com.mycompany.soccergui.dashboard.showJPanel;

/**
 *
 * @author torre
 */
public class matches extends javax.swing.JPanel {

    /**
     * Creates new form playersForm
     */
    public matches() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        saearchFieldMatch = new javax.swing.JTextField();
        searchMatch = new javax.swing.JButton();
        tableMatch = new javax.swing.JScrollPane();
        tablePlayers = new javax.swing.JTable();
        createMatch = new javax.swing.JButton();
        updateMacth = new javax.swing.JButton();
        deleteMacth = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        saearchFieldMatch.setBackground(new java.awt.Color(255, 255, 255));
        saearchFieldMatch.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        saearchFieldMatch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saearchFieldMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        searchMatch.setBackground(new java.awt.Color(255, 0, 0));
        searchMatch.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        searchMatch.setForeground(new java.awt.Color(255, 255, 255));
        searchMatch.setText("Buscar");
        searchMatch.setBorder(new javax.swing.border.MatteBorder(null));
        searchMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMatchActionPerformed(evt);
            }
        });

        tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMatch.setViewportView(tablePlayers);

        createMatch.setBackground(new java.awt.Color(255, 0, 0));
        createMatch.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        createMatch.setForeground(new java.awt.Color(255, 255, 255));
        createMatch.setText("Crear");
        createMatch.setBorder(new javax.swing.border.MatteBorder(null));
        createMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMatchActionPerformed(evt);
            }
        });

        updateMacth.setBackground(new java.awt.Color(255, 0, 0));
        updateMacth.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        updateMacth.setForeground(new java.awt.Color(255, 255, 255));
        updateMacth.setText("Actualizar");
        updateMacth.setBorder(new javax.swing.border.MatteBorder(null));
        updateMacth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateMacth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMacthActionPerformed(evt);
            }
        });

        deleteMacth.setBackground(new java.awt.Color(255, 0, 0));
        deleteMacth.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        deleteMacth.setForeground(new java.awt.Color(255, 255, 255));
        deleteMacth.setText("Borrar");
        deleteMacth.setBorder(new javax.swing.border.MatteBorder(null));
        deleteMacth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteMacth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMacthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateMacth, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteMacth, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(saearchFieldMatch)
                        .addGap(18, 18, 18)
                        .addComponent(searchMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addComponent(tableMatch, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saearchFieldMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(tableMatch, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteMacth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMacth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMatchActionPerformed

    private void createMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMatchActionPerformed
        // TODO add your handling code here:
        showJPanel(new matchesForm());
    }//GEN-LAST:event_createMatchActionPerformed

    private void updateMacthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMacthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateMacthActionPerformed

    private void deleteMacthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMacthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMacthActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createMatch;
    private javax.swing.JButton deleteMacth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField saearchFieldMatch;
    private javax.swing.JButton searchMatch;
    private javax.swing.JScrollPane tableMatch;
    private javax.swing.JTable tablePlayers;
    private javax.swing.JButton updateMacth;
    // End of variables declaration//GEN-END:variables
}
