/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import static com.mycompany.soccergui.dashboard.showJPanel;

/**
 *
 * @author torre
 */
public class presidents extends javax.swing.JPanel {

    /**
     * Creates new form playersForm
     */
    public presidents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchFieldPresident = new javax.swing.JTextField();
        searchPresident = new javax.swing.JButton();
        tablePresident = new javax.swing.JScrollPane();
        tablePlayers = new javax.swing.JTable();
        createPresident = new javax.swing.JButton();
        updatePresident = new javax.swing.JButton();
        deletePresident = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchFieldPresident.setBackground(new java.awt.Color(255, 255, 255));
        searchFieldPresident.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        searchFieldPresident.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchFieldPresident.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        searchPresident.setBackground(new java.awt.Color(255, 0, 0));
        searchPresident.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        searchPresident.setForeground(new java.awt.Color(255, 255, 255));
        searchPresident.setText("Buscar");
        searchPresident.setBorder(new javax.swing.border.MatteBorder(null));
        searchPresident.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchPresident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPresidentActionPerformed(evt);
            }
        });

        tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePresident.setViewportView(tablePlayers);

        createPresident.setBackground(new java.awt.Color(255, 0, 0));
        createPresident.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        createPresident.setForeground(new java.awt.Color(255, 255, 255));
        createPresident.setText("Crear");
        createPresident.setBorder(new javax.swing.border.MatteBorder(null));
        createPresident.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createPresident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPresidentActionPerformed(evt);
            }
        });

        updatePresident.setBackground(new java.awt.Color(255, 0, 0));
        updatePresident.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        updatePresident.setForeground(new java.awt.Color(255, 255, 255));
        updatePresident.setText("Actualizar");
        updatePresident.setBorder(new javax.swing.border.MatteBorder(null));
        updatePresident.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatePresident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePresidentActionPerformed(evt);
            }
        });

        deletePresident.setBackground(new java.awt.Color(255, 0, 0));
        deletePresident.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        deletePresident.setForeground(new java.awt.Color(255, 255, 255));
        deletePresident.setText("Borrar");
        deletePresident.setBorder(new javax.swing.border.MatteBorder(null));
        deletePresident.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletePresident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePresidentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updatePresident, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePresident, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchFieldPresident)
                        .addGap(18, 18, 18)
                        .addComponent(searchPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addComponent(tablePresident, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFieldPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(tablePresident, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePresident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePresident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createPresident, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPresidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPresidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPresidentActionPerformed

    private void createPresidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPresidentActionPerformed
        // TODO add your handling code here:
        showJPanel(new presidentForm());
    }//GEN-LAST:event_createPresidentActionPerformed

    private void updatePresidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePresidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePresidentActionPerformed

    private void deletePresidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePresidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletePresidentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createPresident;
    private javax.swing.JButton deletePresident;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchFieldPresident;
    private javax.swing.JButton searchPresident;
    private javax.swing.JTable tablePlayers;
    private javax.swing.JScrollPane tablePresident;
    private javax.swing.JButton updatePresident;
    // End of variables declaration//GEN-END:variables
}
