/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.views;

import static com.mycompany.soccergui.dashboard.showJPanel;

/**
 *
 * @author torre
 */
public class teams extends javax.swing.JPanel {

    /**
     * Creates new form playersForm
     */
    public teams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchFieldTeams = new javax.swing.JTextField();
        searchTeams = new javax.swing.JButton();
        tableTeams = new javax.swing.JScrollPane();
        tablePlayers = new javax.swing.JTable();
        createTeams = new javax.swing.JButton();
        updateTeams = new javax.swing.JButton();
        deleteTeams = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchFieldTeams.setBackground(new java.awt.Color(255, 255, 255));
        searchFieldTeams.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        searchFieldTeams.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchFieldTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        searchTeams.setBackground(new java.awt.Color(255, 0, 0));
        searchTeams.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        searchTeams.setForeground(new java.awt.Color(255, 255, 255));
        searchTeams.setText("Buscar");
        searchTeams.setBorder(new javax.swing.border.MatteBorder(null));
        searchTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTeamsActionPerformed(evt);
            }
        });

        tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTeams.setViewportView(tablePlayers);

        createTeams.setBackground(new java.awt.Color(255, 0, 0));
        createTeams.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        createTeams.setForeground(new java.awt.Color(255, 255, 255));
        createTeams.setText("Crear");
        createTeams.setBorder(new javax.swing.border.MatteBorder(null));
        createTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamsActionPerformed(evt);
            }
        });

        updateTeams.setBackground(new java.awt.Color(255, 0, 0));
        updateTeams.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        updateTeams.setForeground(new java.awt.Color(255, 255, 255));
        updateTeams.setText("Actualizar");
        updateTeams.setBorder(new javax.swing.border.MatteBorder(null));
        updateTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTeamsActionPerformed(evt);
            }
        });

        deleteTeams.setBackground(new java.awt.Color(255, 0, 0));
        deleteTeams.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        deleteTeams.setForeground(new java.awt.Color(255, 255, 255));
        deleteTeams.setText("Borrar");
        deleteTeams.setBorder(new javax.swing.border.MatteBorder(null));
        deleteTeams.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeamsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(searchFieldTeams)
                        .addGap(18, 18, 18)
                        .addComponent(searchTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addComponent(tableTeams, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFieldTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(tableTeams, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTeamsActionPerformed

    private void createTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamsActionPerformed
        // TODO add your handling code here:
        showJPanel(new teamsForm());
    }//GEN-LAST:event_createTeamsActionPerformed

    private void updateTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateTeamsActionPerformed

    private void deleteTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTeamsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createTeams;
    private javax.swing.JButton deleteTeams;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField searchFieldTeams;
    private javax.swing.JButton searchTeams;
    private javax.swing.JTable tablePlayers;
    private javax.swing.JScrollPane tableTeams;
    private javax.swing.JButton updateTeams;
    // End of variables declaration//GEN-END:variables
}
